"""Precompute and cache Mitchy hints.

Recommended approach: hybrid lazy-precompute.
- Generate hints once with an API provider and store them in DB.
- The use-perk Edge Function only reads cached hints, so exams remain fast and
  available even if provider keys are exhausted.
- Missing hints can be generated by this cron/one-off job before demos.

This script supports level written questions plus module/challenge MCQ questions
if the migration adding `mitchy_hint` columns has been applied.
"""
from __future__ import annotations

import argparse
import json
import logging
import re
from typing import Any, Optional

from scoring.provider_client import generate_text, parse_json_object
from scoring.supabase_utils import get_client

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("hint_generator")

HINT_SCHEMA = {
    "type": "object",
    "properties": {"hint": {"type": "string"}},
    "required": ["hint"],
    "additionalProperties": False,
}

TABLES = {
    "level": {
        "table": "level_assessment_questions",
        "select": "id, question_text, ai_grading_rubric, mitchy_hint",
        "answer_field": "ai_grading_rubric",
        "hint_field": "mitchy_hint",
    },
    "module": {
        "table": "module_assessment_questions",
        "select": "id, question_text, options, correct_answer, mitchy_hint",
        "answer_field": "correct_answer",
        "hint_field": "mitchy_hint",
    },
    "challenge": {
        "table": "challenge_questions",
        "select": "id, question_text, options, correct_answer, mitchy_hint",
        "answer_field": "correct_answer",
        "hint_field": "mitchy_hint",
    },
}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--kind", choices=["level", "module", "challenge"], default=None)
    parser.add_argument("--all", action="store_true", help="process all supported kinds")
    parser.add_argument("--limit", type=int, default=100)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    kinds = list(TABLES) if args.all or not args.kind else [args.kind]
    supabase = get_client()

    total = 0
    for kind in kinds:
        total += process_kind(supabase, kind, limit=args.limit, dry_run=args.dry_run)
    logger.info("hint generation complete: updated=%s dry_run=%s", total, args.dry_run)


def process_kind(supabase, kind: str, *, limit: int, dry_run: bool) -> int:
    cfg = TABLES[kind]
    try:
        res = (
            supabase.table(cfg["table"])
            .select(cfg["select"])
            .or_("mitchy_hint.is.null,mitchy_hint.eq.")
            .limit(limit)
            .execute()
        )
    except Exception as exc:
        logger.warning("Skipping %s: table/column not ready yet (%s)", kind, exc)
        return 0

    rows = res.data or []
    updated = 0
    for row in rows:
        hint = build_hint(kind, row)
        if not hint:
            continue
        logger.info("%s %s -> %s", kind, row["id"], hint)
        if not dry_run:
            supabase.table(cfg["table"]).update({cfg["hint_field"]: hint}).eq("id", row["id"]).execute()
        updated += 1
    return updated


def build_hint(kind: str, row: dict[str, Any]) -> str:
    question = row.get("question_text") or ""
    correct_source = row.get("ai_grading_rubric") or row.get("correct_answer") or ""
    options = row.get("options")

    system = (
        "You are Mitchy, a learning assistant. Create exactly one short hint. "
        "The hint must help the learner think in the right direction but must NOT reveal the final answer directly. "
        "Use simple student-friendly language. Return JSON only."
    )
    user = json.dumps(
        {
            "question_type": kind,
            "question": question,
            "options": options,
            "correct_answer_or_rubric": correct_source,
            "hint_requirements": [
                "one sentence only",
                "do not reveal the answer word-for-word",
                "do not mention that you know the correct answer",
                "for calculation questions, hint the method not the final number",
            ],
        },
        ensure_ascii=False,
    )
    try:
        result = generate_text(system, user, json_schema=HINT_SCHEMA)
        parsed = parse_json_object(result.text)
        hint = sanitize_hint(str(parsed.get("hint", "")))
        if hint:
            return hint
    except Exception as exc:
        logger.warning("provider hint failed for %s: %s", row.get("id"), exc)

    return fallback_hint(kind, question, correct_source)


def sanitize_hint(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip().strip('"')
    if len(text) > 220:
        text = text[:217].rsplit(" ", 1)[0] + "..."
    return text


def fallback_hint(kind: str, question: str, correct_source: Any) -> str:
    q = question.lower()
    if "mean" in q or "median" in q:
        return "Think about whether the question asks for an average or the middle value after sorting."
    if "standard deviation" in q or "spread" in q:
        return "Start by finding the mean, then look at how far each value is from it."
    if "sql" in q or "join" in q:
        return "Ask yourself which table has the main records and which table adds related details."
    if "power bi" in q or "dashboard" in q:
        return "Focus on how raw data becomes a visual report that people can explore."
    if kind == "level":
        return "Break your answer into the main steps from the question, then explain why each step matters."
    return "Eliminate choices that do not match the main idea in the question."


if __name__ == "__main__":
    main()
